### GET all participaciones
http://localhost:3000/api/participaciones


### POST a participacion
# @name createparticipacion
POST http://localhost:3000/api/participaciones
Content-Type: application/json

{
  "puntos": 20,
  "minutosjugados": 30,
  "faltas": 2,
  "partido": 1,
  "usuario": 2

}

### ID
@id = {{createparticipacion.response.body.data.id}}

### GET one participacion
http://localhost:3000/api/participaciones/2

### PUT a participacion
PUT http://localhost:3000/api/participaciones/{{id}}
Content-Type: application/json

{
  "puntos": 25,
  "minutosjugados": 35,
  "faltas": 3,
  "partido": 1,
  "usuario": 2
}

### POST a participacion
POST http://localhost:3000/api/participaciones
Content-Type: application/json

{
  "puntos": 15,
  "minutosjugados": 20
}

### POST a participacion
# @name createParticipacionToDelete
POST http://localhost:3000/api/participaciones
Content-Type: application/json

{
  "puntos": 10,
  "minutosjugados": 15,
  "faltas": 1,
  "partido": 1,
  "usuario": 2
}

### DELETE a participacion
@idToDelete = {{createParticipacionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/participaciones/16

