### GET all noticias
http://localhost:3000/api/noticias


### POST a noticia
# @name createNotiFutbol
POST http://localhost:3000/api/noticias
Content-Type: application/json

{
  "titulo": "Torneo de fútbol regional", 
  "descripcion": "Un torneo emocionante con equipos locales compitiendo por el campeonato."
}

### ID
@id = {{createNotiFutbol.response.body.data.id}}

### GET one noticia
http://localhost:3000/api/noticias/{{id}}

### PUT a noticia
PUT http://localhost:3000/api/noticias/{{id}}
Content-Type: application/json

{
  "titulo": "Torneo de basket nacional",
  "descripcion": "Un torneo emocionante con equipos de todo el país compitiendo por el campeonato."
}



### PATCH a noticia
PATCH http://localhost:3000/api/noticias/{{id}}
Content-Type: application/json

{
  "titulo": "Copa de rugby local - Actualización",
  "descripcion": "Actualización del torneo de rugby con equipos locales."
}

### DELETE a noticia
DELETE http://localhost:3000/api/noticias/{{id}}