### obtener todos los establecimientos
GET http://localhost:3000/api/establecimientos

### crear un nuevo establecimiento
# @name createSomisa
POST http://localhost:3000/api/establecimientos
Content-Type: application/json

{
  "nombre" : "Club Somisa",
  "direccion" : "los ceibos 1950",
  "localidad" : "San Nicolas de los Arroyos"

}

### ID
@id = {{createSomisa.response.body.data.id}}

### obtener un establecimiento
GET http://localhost:3000/api/establecimientos/{{id}}

### modificar un establecimiento (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/establecimientos/{{id}}
Content-Type: application/json

{
  "nombre" : "Club Atletico Rosario",
  "direccion" : "Pasaje Gould 865",
  "localidad" : "Rosario"
}

### modificar un establecimiento (PATCH - recurso parcial)
PATCH http://localhost:3000/api/establecimientos/{{id}}
Content-Type: application/json

{
  "nombre" : "Club Regatas San Nicolas",
  "direccion" : "Juan Manuel de Rosas 100"
}

### borrar un establecimiento
DELETE http://localhost:3000/api/establecimientos/{{id}}