### GET all deportes
http://localhost:3000/api/deportes


### POST a deporte
# @name createFutbol
POST http://localhost:3000/api/deportes
Content-Type: application/json

{
    "nombre": "Futbol",
    "cantMinJugadores": 11,
    "cantMaxJugadores": 11,
    "duracion": 90
}

### ID
@id = {{createFutbol.response.body.data.id}}

### GET one deporte
http://localhost:3000/api/deportes/{{id}}

### PUT a deporte
PUT http://localhost:3000/api/deportes/{{id}}
Content-Type: application/json

{
  "nombre" : "tenis",
  "cantMinJugadores": 2,
  "cantMaxJugadores": 4,
  "duracion": 20
}

### POST a deporte
POST http://localhost:3000/api/deportes
Content-Type: application/json

{
    "nombre": "Rugby",
    "cantMinJugadores": 15,
    "cantMaxJugadores": 15,
    "duracion": 80
}

### POST a deporte
# @name createDeporteToDelete
POST http://localhost:3000/api/deportes
Content-Type: application/json

{
    "nombre": "Basketball",
    "cantMinJugadores": 5,
    "cantMaxJugadores": 5,
    "duracion": 48
}
### DELETE a deporte
@idToDelete = {{createDeporteToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/deportes/{{idToDelete}}

### PATCH a deporte
PATCH http://localhost:3000/api/deportes/{{idToDelete}}
Content-Type: application/json

{
  "nombre" : "tenis cambiado",
  "cantMinJugadores": 2,
  "cantMaxJugadores": 4
}

### DELETE a deporte
DELETE http://localhost:3000/api/deportes/{{idToDelete}}