### crear un nuevo usuario
# @name createJosep
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre" : "Jose",
  "apellido" : "Perez",
  "usuario" : "josep",
  "contraseña" : "123456",
  "email" : "jose@example.com",
  "esAdmin" : false,
  "fechaNacimiento" : "1990-01-01"
}

### POST a deporte
# @name createFutbol
POST http://localhost:3000/api/deportes
Content-Type: application/json

{
    "nombre": "Futbol",
    "cantMinJugadores": 11,
    "cantMaxJugadores": 11,
    "duracion": 90
}

### crear un nuevo establecimiento
# @name createSomisa
POST http://localhost:3000/api/establecimientos
Content-Type: application/json

{
  "nombre" : "Club Somisa",
  "direccion" : "los ceibos 1950",
  "localidad" : "San Nicolas de los Arroyos"

}

### POST a evento
# @name createEvento
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
    "nombre": "Mundial FIFA",
    "esPublico": true,
    "cantEquiposMax": 32,
    "contraseña": "1234",
    "fechaInicioInscripcion": "2025-10-01T00:00:00Z",
    "fechaFinInscripcion": "2025-10-15T00:00:00Z",
    "fechaInicioEvento": "2025-11-01T00:00:00Z",
    "fechaFinEvento": "2025-12-01T00:00:00Z",
    "deporte": 1
}

### crear un nuevo equipo
# @name createEquipo
POST http://localhost:3000/api/equipos
Content-Type: application/json

{
  "nombre" : "Real Madrid",
  "nombreCapitan" : "Daniel Carvajal",
  "puntos" : 999,
  "esPublico": true,
  "contraseña": "1234",
  "evento": 1,
  "miembros" : [1] 
}

### POST a partido
# @name createPartido
POST http://localhost:3000/api/partidos
Content-Type: application/json

{
    "fecha": "2025-11-15",
    "hora": "15:00",
    "juez": "Juan Perez",
    "resultado": "2-1",
    "equipoLocal": 1,
    "equipoVisitante": 1,
    "mvp": 1,
    "maxAnotador": 1,
    "evento": 1,
    "establecimiento": 1
}

### GET all usuarios
http://localhost:3000/api/usuarios

### GET all eventos
http://localhost:3000/api/eventos

### GET all partidos
http://localhost:3000/api/partidos

### GET all equipos
http://localhost:3000/api/equipos

### GET all deportes
http://localhost:3000/api/deportes

### GET all establecimientos
http://localhost:3000/api/establecimientos
